export const SHOP_DATA = [
  {
    title: "hustle_and_bustle",
    items: [
      {
        id: 1,
        name: "Ice Cream Dance",
        imageUrl: "https://i.ibb.co/S6g7ffS/000798030019.jpg",
        price: 20,
      },
      {
        id: 2,
        name: "Umbrella",
        imageUrl: "https://i.ibb.co/Hr5b42V/umbrella.jpg",
        price: 22,
      },
      {
        id: 3,
        name: "Observers",
        imageUrl: "https://i.ibb.co/ZhTBtbH/observers.jpg",
        price: 32,
      },
      {
        id: 4,
        name: "Sportsmanship",
        imageUrl: "https://i.ibb.co/qYnxXnL/nolook.jpg",
        price: 24,
      },
      {
        id: 5,
        name: "Hat's Off",
        imageUrl: "https://i.ibb.co/Q6D0CDd/hatsoff.jpg",
        price: 18,
      },
      {
        id: 6,
        name: "Green Men",
        imageUrl: "https://i.ibb.co/FBszKbn/green.jpg",
        price: 22,
      },
      {
        id: 7,
        name: "Family Band",
        imageUrl: "https://i.ibb.co/Jr1wSgW/family.jpg",
        price: 18,
      },
      {
        id: 8,
        name: "Drop Dead",
        imageUrl: "https://i.ibb.co/CVS1qrk/dropdead.jpg",
        price: 22,
      },
      {
        id: 9,
        name: "Space Baby",
        imageUrl: "https://i.ibb.co/0fYqrwY/daddy.jpg",
        price: 16,
      },
      {
        id: 10,
        name: "Party Trick",
        imageUrl: "https://i.ibb.co/NKN90NL/clown.jpg",
        price: 18,
      },
      {
        id: 11,
        name: "Air Born",
        imageUrl: "https://i.ibb.co/5hRWLvL/airtravel.jpg",
        price: 23,
      },
      {
        id: 12,
        name: "Bags",
        imageUrl: "https://i.ibb.co/Twnhszd/bags.jpg",
        price: 19,
      },
    ],
  },
  {
    title: "time_travel",
    items: [
      {
        id: 13,
        name: "Vacancy",
        imageUrl: "https://i.ibb.co/G70P6Zr/vacancy.jpg",
        price: 28,
      },
      {
        id: 14,
        name: "Toilet",
        imageUrl: "https://i.ibb.co/jfJ0bPt/toilet.jpg",
        price: 28,
      },
      {
        id: 15,
        name: "Tavern",
        imageUrl: "https://i.ibb.co/NF7Ct4k/tavern.jpg",
        price: 21,
      },
      {
        id: 16,
        name: "Motel",
        imageUrl: "https://i.ibb.co/xSXzhBQ/motel.jpg",
        price: 16,
      },
      {
        id: 17,
        name: "Sweet Home",
        imageUrl: "https://i.ibb.co/9tvSWDk/kitchen.jpg",
        price: 18,
      },
      {
        id: 18,
        name: "Coca Cola",
        imageUrl: "https://i.ibb.co/9yXf9BR/cokecola.jpg",
        price: 28,
      },
      {
        id: 19,
        name: "Basket Board",
        imageUrl: "https://i.ibb.co/0cHYKK9/basket.jpg",
        price: 19,
      },
      {
        id: 20,
        name: "911",
        imageUrl: "https://i.ibb.co/82c03Lz/911.jpg",
        price: 40,
      },
    ],
  },
  {
    title: "light_seeker",
    items: [
      {
        id: 21,
        name: "Steps to Heaven",
        imageUrl: "https://i.ibb.co/D7THj4y/steps-to-heaven.jpg",
        price: 15,
      },
      {
        id: 22,
        name: "Skater",
        imageUrl: "https://i.ibb.co/TKGCfmj/light-skater.jpg",
        price: 12,
      },
      {
        id: 23,
        name: "Road to Hell",
        imageUrl: "https://i.ibb.co/C18xSy8/roadtohell.jpg",
        price: 19,
      },
      {
        id: 24,
        name: "Library",
        imageUrl: "https://i.ibb.co/MMQkKRL/library.jpg",
        price: 16,
      },
      {
        id: 25,
        name: "Green House",
        imageUrl: "https://i.ibb.co/KVBKbJD/house.jpg",
        price: 18,
      },
      {
        id: 26,
        name: "Corner",
        imageUrl: "https://i.ibb.co/nPzZYfz/corner.jpg",
        price: 12,
      },
      {
        id: 27,
        name: "Boat",
        imageUrl: "https://i.ibb.co/f8m54sj/boat.jpg",
        price: 22,
      },
    ],
  },
  {
    title: "near_mountain",
    items: [
      {
        id: 28,
        name: "Mansion",
        imageUrl: "https://i.ibb.co/X4kx49H/walkingdown.jpg",
        price: 25,
      },
      {
        id: 29,
        name: "Lake",
        imageUrl: "https://i.ibb.co/54gjfBW/reflection.jpg",
        price: 28,
      },
      {
        id: 30,
        name: "Neon",
        imageUrl: "https://i.ibb.co/q1zLt2H/neon.jpg",
        price: 38,
      },
      {
        id: 31,
        name: "Horizon",
        imageUrl: "https://i.ibb.co/HDxzRgk/horizon.jpg",
        price: 18,
      },
      {
        id: 32,
        name: "Emerald",
        imageUrl: "https://i.ibb.co/16S73zs/emerald.jpg",
        price: 24,
      },
      {
        id: 33,
        name: "Conversation",
        imageUrl: "https://i.ibb.co/PW8g8Jd/conversation.jpg",
        price: 33,
      },
      {
        id: 34,
        name: "Distilled",
        imageUrl: "https://i.ibb.co/0qv2gqW/distilled.jpg",
        price: 20,
      },
    ],
  },
  {
    title: "by_the_sea",
    items: [
      {
        id: 35,
        name: "Wave",
        imageUrl: "https://i.ibb.co/rHM16y3/wave.jpg",
        price: 32,
      },
      {
        id: 36,
        name: "Waiting",
        imageUrl: "https://i.ibb.co/Js0NQMJ/waiting.jpg",
        price: 29,
      },
      {
        id: 37,
        name: "Target",
        imageUrl: "https://i.ibb.co/PrDnwB6/target.jpg",
        price: 25,
      },
      {
        id: 38,
        name: "Sunset",
        imageUrl: "https://i.ibb.co/pxLtS38/sunset.jpg",
        price: 25,
      },
      {
        id: 39,
        name: "Pairs",
        imageUrl: "https://i.ibb.co/CVn7bPc/pair.jpg",
        price: 40,
      },
      {
        id: 40,
        name: "Loyal Friend",
        imageUrl: "https://i.ibb.co/yRrYBPg/doggy.jpg",
        price: 25,
      },
      {
        id: 41,
        name: "Misty Town",
        imageUrl: "https://i.ibb.co/ctYc5yV/misttown.jpg",
        price: 26,
      },
      {
        id: 42,
        name: "Businessman",
        imageUrl: "https://i.ibb.co/RHkXPgD/businessman.jpg",
        price: 21,
      },
      {
        id: 42,
        name: "Beacon",
        imageUrl: "https://i.ibb.co/b17YkbS/beacon.jpg",
        price: 23,
      },
    ],
  },
];
